/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NameMaker {
    }
}
declare global {
    interface HTMLNameMakerElement extends Components.NameMaker, HTMLStencilElement {
    }
    var HTMLNameMakerElement: {
        prototype: HTMLNameMakerElement;
        new (): HTMLNameMakerElement;
    };
    interface HTMLElementTagNameMap {
        "name-maker": HTMLNameMakerElement;
    }
}
declare namespace LocalJSX {
    interface NameMaker {
    }
    interface IntrinsicElements {
        "name-maker": NameMaker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "name-maker": LocalJSX.NameMaker & JSXBase.HTMLAttributes<HTMLNameMakerElement>;
        }
    }
}
